version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /soku
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /templates/javascript-typescript-node
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /templates/python
    schedule:
      interval: monthly
