#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/cd-deploy.sh \
  --plan-file <path> \
  [--health-path /health] \
  [--health-attempts 18] \
  [--health-delay 10] \
  [--identity-service-account <email>] \
  [--rollback-only] \
  [--rollback-revision <revision>] \
  [--confirm]

Deploys with the same plan generated by cd-plan.sh using Cloud Run.

Options:
  --plan-file <path>        Required. Plan file generated by cd-plan.sh.
  --health-path <path>      Health endpoint path. Default: /health.
  --health-attempts <n>     Number of healthcheck retries. Default: 18.
  --health-delay <sec>      Delay between retries. Default: 10.
  --identity-service-account <email>
                            Optional service account impersonated when minting
                            the private Cloud Run health-check identity token.
  --rollback-only           Perform manual rollback and skip new deployment.
  --rollback-revision <rev> Target revision for rollback.
  --confirm                 Skip manual confirmation prompt.
  --help                    Show this help and exit.
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

PLAN_FILE=""
HEALTH_PATH="/health"
HEALTH_ATTEMPTS=18
HEALTH_DELAY=10
IDENTITY_SERVICE_ACCOUNT=""
ROLLBACK_ONLY=false
ROLLBACK_REVISION=""
CONFIRM=false

while ((${#})); do
  case "$1" in
    --plan-file)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --plan-file" >&2
        usage
        exit 2
      fi
      PLAN_FILE="$2"
      shift 2
      ;;
    --health-path)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --health-path" >&2
        usage
        exit 2
      fi
      HEALTH_PATH="$2"
      shift 2
      ;;
    --health-attempts)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --health-attempts" >&2
        usage
        exit 2
      fi
      HEALTH_ATTEMPTS="$2"
      shift 2
      ;;
    --health-delay)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --health-delay" >&2
        usage
        exit 2
      fi
      HEALTH_DELAY="$2"
      shift 2
      ;;
    --identity-service-account)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --identity-service-account" >&2
        usage
        exit 2
      fi
      IDENTITY_SERVICE_ACCOUNT="$2"
      shift 2
      ;;
    --rollback-only)
      ROLLBACK_ONLY=true
      shift
      ;;
    --rollback-revision)
      if [[ "${2-}" == "" ]]; then
        echo "Missing value for --rollback-revision" >&2
        usage
        exit 2
      fi
      ROLLBACK_REVISION="$2"
      shift 2
      ;;
    --confirm)
      CONFIRM=true
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -n "$IDENTITY_SERVICE_ACCOUNT" &&
  ! "$IDENTITY_SERVICE_ACCOUNT" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*@[a-zA-Z0-9][a-zA-Z0-9.-]*\.gserviceaccount\.com$ ]]; then
  echo "--identity-service-account must be a Google service-account email" >&2
  exit 2
fi

if [[ -z "$PLAN_FILE" || ! -f "$PLAN_FILE" ]]; then
  echo "--plan-file is required and must exist" >&2
  usage
  exit 2
fi

require_cmd() {
  local cmd="$1"
  local step="$2"
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "Error: $step requires '$cmd'" >&2
    exit 3
  }
}

require_plan_value() {
  local value="$1"
  local name="$2"
  if [[ -z "$value" ]]; then
    echo "Plan file is missing required key: $name" >&2
    exit 4
  fi
}

load_plan_value() {
  local key="$1"
  while IFS= read -r line; do
    if [[ "$line" == "$key="* ]]; then
      echo "${line#*=}"
      return 0
    fi
  done < "$PLAN_FILE"
  echo ""
}

normalize_health_path() {
  local path="$1"
  [[ "$path" == /* ]] || path="/$path"
  echo "$path"
}

require_cmd gcloud "cd-deploy"
require_cmd jq "cd-deploy"
require_cmd curl "cd-deploy"

CD_PLAN_ENVIRONMENT="$(load_plan_value CD_PLAN_ENVIRONMENT)"
CD_PLAN_COMMIT_SHA="$(load_plan_value CD_PLAN_COMMIT_SHA)"
CD_PLAN_IMAGE_URI="$(load_plan_value CD_PLAN_IMAGE_URI)"
CD_PLAN_IMAGE_TAG_URI="$(load_plan_value CD_PLAN_IMAGE_TAG_URI)"
CD_PLAN_PROJECT_ID="$(load_plan_value CD_PLAN_PROJECT_ID)"
CD_PLAN_REGION="$(load_plan_value CD_PLAN_REGION)"
CD_PLAN_SERVICE_NAME="$(load_plan_value CD_PLAN_SERVICE_NAME)"

require_plan_value "$CD_PLAN_ENVIRONMENT" CD_PLAN_ENVIRONMENT
require_plan_value "$CD_PLAN_COMMIT_SHA" CD_PLAN_COMMIT_SHA
if [[ "$ROLLBACK_ONLY" != true ]]; then
  require_plan_value "$CD_PLAN_IMAGE_URI" CD_PLAN_IMAGE_URI
  if [[ ! "$CD_PLAN_IMAGE_URI" =~ @sha256:[0-9a-fA-F]{64}$ ]]; then
    echo "Plan image must be an immutable repository digest URI" >&2
    exit 4
  fi
fi
require_plan_value "$CD_PLAN_PROJECT_ID" CD_PLAN_PROJECT_ID
require_plan_value "$CD_PLAN_REGION" CD_PLAN_REGION
require_plan_value "$CD_PLAN_SERVICE_NAME" CD_PLAN_SERVICE_NAME

prompt_confirm() {
  if [[ "$CONFIRM" == true || "${CI:-}" == "true" ]]; then
    return 0
  fi

  printf 'Type DEPLOY to continue deployment for %s: ' "$CD_PLAN_SERVICE_NAME"
  read -r answer
  if [[ "$answer" != "DEPLOY" ]]; then
    echo "Deployment cancelled by user"
    exit 0
  fi
}

get_current_revision() {
  gcloud run services describe "$CD_PLAN_SERVICE_NAME" \
    --project "$CD_PLAN_PROJECT_ID" \
    --region "$CD_PLAN_REGION" \
    --platform managed \
    --format='value(status.latestReadyRevisionName)' || true
}

get_service_url() {
  gcloud run services describe "$CD_PLAN_SERVICE_NAME" \
    --project "$CD_PLAN_PROJECT_ID" \
    --region "$CD_PLAN_REGION" \
    --platform managed \
    --format='value(status.url)'
}

get_previous_ready_revision() {
  local latest="$1"
  local revisions

  readarray -t revisions < <(
    gcloud run revisions list "$CD_PLAN_SERVICE_NAME" \
      --project "$CD_PLAN_PROJECT_ID" \
      --region "$CD_PLAN_REGION" \
      --platform managed \
      --sort-by='~metadata.createTime' \
      --format='value(metadata.name)'
  )

  for revision in "${revisions[@]}"; do
    if [[ -n "$revision" && "$revision" != "$latest" ]]; then
      echo "$revision"
      return 0
    fi
  done

  return 1
}

set_traffic_revision() {
  local revision="$1"

  gcloud run services update-traffic "$CD_PLAN_SERVICE_NAME" \
    --project "$CD_PLAN_PROJECT_ID" \
    --region "$CD_PLAN_REGION" \
    --platform managed \
    --to-revisions="${revision}=100" \
    --quiet
}

run_health_check() {
  local service_url="$1"
  local attempt=1
  local identity_token=""
  local path

  path="$(normalize_health_path "$HEALTH_PATH")"

  if [[ -z "$service_url" ]]; then
    return 1
  fi

  local token_args=()
  if [[ -n "$IDENTITY_SERVICE_ACCOUNT" ]]; then
    token_args+=(--impersonate-service-account="$IDENTITY_SERVICE_ACCOUNT")
  fi
  token_args+=(--audiences="${service_url%/}")

  if ! identity_token="$(gcloud auth print-identity-token "${token_args[@]}")" ||
    [[ -z "$identity_token" ]]; then
    echo "Unable to acquire an identity token for the private Cloud Run health check" >&2
    return 1
  fi

  while ((attempt <= HEALTH_ATTEMPTS)); do
    if curl -fsS --max-time 10 \
      --header "Authorization: Bearer $identity_token" \
      "${service_url%/}${path}" >/dev/null 2>&1; then
      echo "Health check passed on attempt $attempt"
      return 0
    fi

    echo "Health check failed on attempt $attempt of $HEALTH_ATTEMPTS"
    attempt=$((attempt + 1))
    sleep "$HEALTH_DELAY"
  done

  echo "Health check did not pass after $HEALTH_ATTEMPTS attempts" >&2
  return 1
}

record_evidence() {
  local status="$1"
  local summary_file="$2"
  local previous_revision="$3"
  local new_revision="$4"
  local error_message="$5"
  local rollback_target="${6:-}"

  jq -n \
    --arg environment "$CD_PLAN_ENVIRONMENT" \
    --arg commit "$CD_PLAN_COMMIT_SHA" \
    --arg project_id "$CD_PLAN_PROJECT_ID" \
    --arg region "$CD_PLAN_REGION" \
    --arg service_name "$CD_PLAN_SERVICE_NAME" \
    --arg image_tag_uri "$CD_PLAN_IMAGE_TAG_URI" \
    --arg image_digest_uri "$CD_PLAN_IMAGE_URI" \
    --arg previous_revision "$previous_revision" \
    --arg new_revision "$new_revision" \
    --arg rollback_target "$rollback_target" \
    --arg status "$status" \
    --arg error "$error_message" \
    --arg actor "${GITHUB_ACTOR:-}" \
    --arg run_id "${GITHUB_RUN_ID:-}" \
    --arg run_attempt "${GITHUB_RUN_ATTEMPT:-}" \
    --arg run_url "${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-}" \
    '{
      environment: $environment,
      final_status: $status,
      commit: $commit,
      project_id: $project_id,
      region: $region,
      service_name: $service_name,
      image_tag_uri: $image_tag_uri,
      image_digest_uri: $image_digest_uri,
      pre_deploy_revision: $previous_revision,
      new_revision: $new_revision,
      rollback_target: $rollback_target,
      error: $error,
      actor: $actor,
      run_id: $run_id,
      run_attempt: $run_attempt,
      run_url: $run_url,
      timestamp: now
    }' > "$summary_file"
}

get_evidence_file() {
  local output_dir="${CD_DEPLOY_EVIDENCE_DIR:-$REPO_ROOT/deploy-evidence}"
  mkdir -p "$output_dir"
  local safe_env="${CD_PLAN_ENVIRONMENT//[^a-zA-Z0-9_-]/_}"
  local safe_run="${GITHUB_RUN_ID:-manual}"
  local safe_attempt="${GITHUB_RUN_ATTEMPT:-1}"
  echo "$output_dir/deploy-${safe_env}-${safe_run}-${safe_attempt}.json"
}

write_step_summary() {
  local status="$1"
  local previous_revision="$2"
  local new_revision="$3"
  local service_url="$4"

  if [[ -z "${GITHUB_STEP_SUMMARY:-}" ]]; then
    return 0
  fi

  {
    echo "### Cloud Run deployment evidence"
    echo "- Environment: $CD_PLAN_ENVIRONMENT"
    echo "- Status: $status"
    echo "- Service: $CD_PLAN_SERVICE_NAME"
    echo "- Commit: $CD_PLAN_COMMIT_SHA"
    echo "- Image: $CD_PLAN_IMAGE_URI"
    echo "- Previous revision: ${previous_revision:-<none>}"
    echo "- New revision: ${new_revision:-<none>}"
    if [[ -n "$service_url" ]]; then
      echo "- Service URL: $service_url"
    fi
  } >> "$GITHUB_STEP_SUMMARY"
}

perform_deploy() {
  local evidence_file
  evidence_file="$(get_evidence_file)"
  local previous_revision=""
  local new_revision=""
  local service_url=""

  previous_revision="$(get_current_revision)"
  echo "Current revision before deploy: ${previous_revision:-<none>}"

  if ! gcloud run deploy "$CD_PLAN_SERVICE_NAME" \
    --project "$CD_PLAN_PROJECT_ID" \
    --region "$CD_PLAN_REGION" \
    --platform managed \
    --image "$CD_PLAN_IMAGE_URI" \
    --quiet; then
    record_evidence "failed" "$evidence_file" "$previous_revision" "" "deploy-command-failed"
    write_step_summary "failed" "$previous_revision" "" ""
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
      echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
    fi
    exit 9
  fi

  new_revision="$(get_current_revision)"
  service_url="$(get_service_url)"
  if [[ -z "$service_url" ]]; then
    record_evidence "failed" "$evidence_file" "$previous_revision" "$new_revision" "service-url-missing"
    write_step_summary "failed" "$previous_revision" "$new_revision" "$service_url"
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
      echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
    fi
    exit 9
  fi

  if ! run_health_check "$service_url"; then
    local rollback_target

    if [[ -n "$previous_revision" ]]; then
      rollback_target="$previous_revision"
      if [[ -n "$rollback_target" ]]; then
        if set_traffic_revision "$rollback_target"; then
          new_revision="$(get_current_revision)"
          service_url="$(get_service_url)"
          if run_health_check "$service_url"; then
            record_evidence "rolled-back" "$evidence_file" "$previous_revision" "$new_revision" "deploy-failed-healthcheck" "$rollback_target"
            write_step_summary "rolled-back" "$previous_revision" "$rollback_target" "$service_url"
            if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
              echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
            fi
            exit 1
          fi
        fi
      fi
    fi

    record_evidence "failed" "$evidence_file" "$previous_revision" "$new_revision" "deploy-failed-healthcheck-and-rollback-failed" "${rollback_target:-}"
    write_step_summary "failed" "$previous_revision" "$new_revision" "$service_url"
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
      echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
    fi
    exit 9
  fi

  record_evidence "success" "$evidence_file" "$previous_revision" "$new_revision" ""
  write_step_summary "success" "$previous_revision" "$new_revision" "$service_url"

  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    {
      echo "evidence_file=$evidence_file"
      echo "status=success"
      echo "service_name=$CD_PLAN_SERVICE_NAME"
      echo "environment=$CD_PLAN_ENVIRONMENT"
    } >> "$GITHUB_OUTPUT"
  fi

  echo "Deployment complete: $CD_PLAN_SERVICE_NAME -> $new_revision"
  echo "Service URL: $service_url"
}

perform_manual_rollback() {
  local evidence_file
  evidence_file="$(get_evidence_file)"
  local current_revision
  local target_revision="$ROLLBACK_REVISION"
  local service_url=""

  current_revision="$(get_current_revision)"
  if [[ -z "$target_revision" ]]; then
    target_revision="$(get_previous_ready_revision "$current_revision" || true)"
  fi

  if [[ -z "$target_revision" ]]; then
    record_evidence "manual-rollback-failed" "$evidence_file" "${current_revision:-}" "" "missing-revision" ""
    write_step_summary "manual-rollback-failed" "" "" ""
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
      echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
    fi
    echo "No previous revision found for rollback target" >&2
    exit 4
  fi

  if set_traffic_revision "$target_revision"; then
    service_url="$(get_service_url)"
    if run_health_check "$service_url"; then
      record_evidence "manual-rollback" "$evidence_file" "${current_revision:-}" "" "" "$target_revision"
      write_step_summary "manual-rollback" "" "$target_revision" "$service_url"
      if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
        {
          echo "evidence_file=$evidence_file"
          echo "status=manual-rollback"
        } >> "$GITHUB_OUTPUT"
      fi
      echo "Manual rollback complete to $target_revision"
      return 0
    fi

    record_evidence "manual-rollback-failed" "$evidence_file" "${current_revision:-}" "" "healthcheck-failed" "$target_revision"
    write_step_summary "manual-rollback-failed" "" "$target_revision" "$service_url"
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
      echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
    fi
    exit 9
  fi

  record_evidence "manual-rollback-failed" "$evidence_file" "${current_revision:-}" "" "update-traffic-failed" "$target_revision"
  write_step_summary "manual-rollback-failed" "" "$target_revision" "$service_url"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "evidence_file=$evidence_file" >> "$GITHUB_OUTPUT"
  fi
  exit 9
}

if [[ "$ROLLBACK_ONLY" == true ]]; then
  perform_manual_rollback
  exit 0
fi

prompt_confirm
perform_deploy
